import assert from "node:assert/strict";
import { request } from "node:http";
import { LocalMasterLibraryBrowserServer } from "../dist/index.js";
const auth = { async login(email, password) { return email === "admin@knowledgeos.local" && password === "password" ? { sessionId: "s1", credential: "token", expiresAt: Date.now() + 60_000 } : undefined; }, async authenticate(value) { return value === "Bearer token" ? "admin@knowledgeos.local" : undefined; }, logout() {} };
const calls = [];
const readStream = async (stream) => {
  if (!stream || typeof stream.on !== "function") return undefined;
  const chunks = [];
  await new Promise((resolve, reject) => { stream.on("data", chunk => chunks.push(Buffer.from(chunk))); stream.once("end", resolve); stream.once("error", reject); });
  return Buffer.concat(chunks).toString("utf8");
};
const fetcher = async (path, init) => {
  const streamedBody = await readStream(init.body);
  calls.push({ path, init: { ...init, streamedBody } });
  if (path === "/v1/master-library/catalog") return { status: 200, body: { items: [{ publicationId: "publication:a" }] } };
  if (path === "/v1/master-library/acquisitions") return { status: 202, body: { receipt: { accepted: true }, manifest: { publicationId: "publication:a" } } };
  if (path === "/v1/master-library/publications:ingest") return { status: 202, body: { operationId: "operation:ingest-1", publicationId: "publication:book-1", versionId: "version:book-1", knowledgeObjectId: "knowledge-object:book-1", outcome: "registered" } };
  if (path === "/v1/master-library/ingest-operations/operation%3Aingest-1") return { status: 200, body: { operationId: "operation:ingest-1", state: "registered", outcome: "registered" } };
  if (path.includes("forbidden")) return { status: 403, body: { error: { code: "authorization.denied", token: "token", path: "/var/lib/knowledgeos/source.pdf" } } };
  return { status: 503, body: { error: { code: "infrastructure.transient" } } };
};
const server = new LocalMasterLibraryBrowserServer({ auth, fetcher, expectedOrigin: "https://localhost:8443" }, { host: "127.0.0.1", port: 0 });
const address = await server.start();
const call = (method, path, headers = {}, body) => new Promise((resolve, reject) => { const req = request({ host: address.host, port: address.port, method, path, headers }, res => { const chunks=[]; res.on("data", c => chunks.push(c)); res.on("end", () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks).toString() })); }); req.once("error", reject); if (body) req.write(body); req.end(); });
try {
  const denied = await call("GET", "/local/api/catalog"); assert.equal(denied.status, 401);
  const wrong = await call("POST", "/local/auth/login", { origin: "https://localhost:8443", "content-type": "application/json" }, JSON.stringify({ email: "admin@knowledgeos.local", password: "wrong" })); assert.equal(wrong.status, 401);
  const badOrigin = await call("POST", "/local/auth/login", { origin: "https://evil.example", "content-type": "application/json" }, JSON.stringify({ email: "admin@knowledgeos.local", password: "password" })); assert.equal(badOrigin.status, 403);
  const login = await call("POST", "/local/auth/login", { origin: "https://localhost:8443", "content-type": "application/json" }, JSON.stringify({ email: "admin@knowledgeos.local", password: "password" })); assert.equal(login.status, 204); assert.match(String(login.headers["set-cookie"]), /HttpOnly; Secure; SameSite=Strict/);
  const cookie = String(login.headers["set-cookie"]).split(";", 1)[0];
  const catalog = await call("GET", "/local/api/catalog", { cookie }); assert.equal(catalog.status, 200); assert.equal(JSON.parse(catalog.body).items[0].publicationId, "publication:a"); assert.equal(calls.length, 1);
  const acquisition = await call("POST", "/local/api/acquisitions", { cookie, origin: "https://localhost:8443", "content-type": "application/json", "idempotency-key": "acquisition-1" }, JSON.stringify({ publicationId: "publication:a", versionId: "version:a", targetLocalLibraryId: "local-library:one" })); assert.equal(acquisition.status, 202); assert.equal(calls.at(-1).init.idempotencyKey, "acquisition-1"); assert.equal(JSON.parse(calls.at(-1).init.body).targetLocalLibraryId, "local-library:one");
  const unavailable = await call("GET", "/local/api/publications/publication%3Aa/versions/version%3Aa/content", { cookie }); assert.equal(unavailable.status, 503); assert.equal(calls.length, 3);
  const forbidden = await call("GET", "/local/api/publications/forbidden/versions/version%3Aa/content", { cookie }); assert.equal(forbidden.status, 403); assert.match(String(forbidden.headers["set-cookie"]), /Max-Age=0/); assert.doesNotMatch(forbidden.body, /token|\/var\/lib\/knowledgeos/i); assert.equal((await call("GET", "/local/api/catalog", { cookie })).status, 401);
  const loginAgain = await call("POST", "/local/auth/login", { origin: "https://localhost:8443", "content-type": "application/json" }, JSON.stringify({ email: "admin@knowledgeos.local", password: "password" })); const nextCookie = String(loginAgain.headers["set-cookie"]).split(";", 1)[0];
  const logout = await call("POST", "/local/auth/logout", { cookie: nextCookie, origin: "https://localhost:8443" }); assert.equal(logout.status, 204); assert.match(String(logout.headers["set-cookie"]), /Max-Age=0/);
  assert.equal((await call("GET", "/local/api/catalog", { cookie: nextCookie })).status, 401);
  // PR3 RED: the local BFF must render a same-origin browser panel without exposing credentials.
  const panel = await call("GET", "/");
  assert.equal(panel.status, 200);
  assert.match(panel.headers["content-type"], /text\/html/);
  assert.match(panel.body, /Local Master Library/);
  assert.match(panel.body, /<script[^>]+src="\/app\.js"/);
  const script = await call("GET", "/app.js");
  assert.equal(script.status, 200);
  assert.match(script.headers["content-type"], /javascript/);
  assert.match(script.body, /local\/api\/catalog/);
  // PR3 RED: an authenticated same-origin browser upload must stream multipart bytes and forward only server-held credentials.
  const boundary = "browser-test-boundary";
  const multipart = `--${boundary}\r\nContent-Disposition: form-data; name="metadata"\r\n\r\n{"title":"A local book","authors":["Operator"]}\r\n--${boundary}\r\nContent-Disposition: form-data; name="source"; filename="book.pdf"\r\nContent-Type: application/pdf\r\n\r\n%PDF-local-book\r\n--${boundary}--\r\n`;
  const unauthenticatedIngest = await call("POST", "/local/api/publications:ingest", { origin: "https://localhost:8443", "content-type": `multipart/form-data; boundary=${boundary}` }, multipart);
  assert.equal(unauthenticatedIngest.status, 401);
  const deniedIngest = await call("POST", "/local/api/publications:ingest", { cookie, origin: "https://evil.example", "content-type": `multipart/form-data; boundary=${boundary}` }, multipart);
  assert.equal(deniedIngest.status, 403);
  const uploadLogin = await call("POST", "/local/auth/login", { origin: "https://localhost:8443", "content-type": "application/json" }, JSON.stringify({ email: "admin@knowledgeos.local", password: "password" }));
  const uploadCookie = String(uploadLogin.headers["set-cookie"]).split(";", 1)[0];
  const ingest = await call("POST", "/local/api/publications:ingest", { cookie: uploadCookie, origin: "https://localhost:8443", "content-type": `multipart/form-data; boundary=${boundary}`, "content-length": String(Buffer.byteLength(multipart)), "idempotency-key": "ingest-1" }, multipart);
  assert.equal(ingest.status, 202);
  const ingestCall = calls.at(-1);
  assert.equal(ingestCall.path, "/v1/master-library/publications:ingest");
  assert.equal(ingestCall.init.contentType, `multipart/form-data; boundary=${boundary}`);
  assert.equal(ingestCall.init.contentLength, String(Buffer.byteLength(multipart)));
  assert.equal(ingestCall.init.idempotencyKey, "ingest-1");
  assert.match(ingestCall.init.streamedBody, /%PDF-local-book/);
  assert.doesNotMatch(ingest.body, /token|\/var\/lib\/knowledgeos/i);
  const operation = await call("GET", "/local/api/ingest-operations/operation%3Aingest-1", { cookie: uploadCookie });
  assert.equal(operation.status, 200);
  assert.equal(JSON.parse(operation.body).state, "registered");
  const updatedPanel = await call("GET", "/");
  assert.match(updatedPanel.body, /Upload PDF or EPUB/);
  assert.match(updatedPanel.body, /id="ingest-form"/);
  assert.match(script.body, /local\/api\/publications:ingest/);
  assert.match(script.body, /Catalog refreshed/);
  assert.match(script.body, /Recovery is in progress/);
  assert.match(script.body, /ingest\.validation-failed/);
  assert.match(script.body, /infrastructure\.transient/);
  assert.match(script.body, /originalFilename: source\.name/);
  assert.match(script.body, /declaredMediaType/);
  assert.match(script.body, /byteLength: source\.size/);
} finally { await server.stop(); }
