import { createServer } from "node:http";
import type { UnifiedSearchExecutionRuntime, SearchExecutionRequest } from "@knowledgeos/search-execution-runtime";
import { encodeSearchBatchNdjson } from "@knowledgeos/search-transport";
export interface SearchHttpPrincipalResolver { authorize(header:string|undefined):Promise<void>; }
export class SearchRuntimeHttpServer {
 public constructor(private readonly runtime:UnifiedSearchExecutionRuntime,private readonly auth:SearchHttpPrincipalResolver,private readonly options:{host:string;port:number;maximumBodyBytes:number}){}
 async start(){const server=createServer(async(req,res)=>{try{await this.auth.authorize(typeof req.headers.authorization==="string"?req.headers.authorization:undefined);const url=new URL(req.url??"/","http://localhost");if(req.method==="GET"&&url.pathname==="/v1/search/health"){res.statusCode=200;res.setHeader("content-type","application/json");res.end(JSON.stringify({status:"ok"}));return;}if(req.method==="POST"&&url.pathname==="/v1/search/cancel"){const body=await this.read(req);this.runtime.cancel(String(body.sessionId));res.statusCode=202;res.end();return;}if(req.method==="POST"&&url.pathname==="/v1/search/stream"){const body=await this.read(req) as SearchExecutionRequest;res.statusCode=200;res.setHeader("content-type","application/x-ndjson");await this.runtime.execute(body,{async publish(batch){res.write(encodeSearchBatchNdjson(batch));}});res.end();return;}res.statusCode=404;res.end(JSON.stringify({error:"not-found"}));}catch(error){res.statusCode=400;res.setHeader("content-type","application/json");res.end(JSON.stringify({error:error instanceof Error?error.message:"unknown-error"}));}});await new Promise<void>(resolve=>server.listen(this.options.port,this.options.host,resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("Unable to resolve address");return{host:address.address,port:address.port,async stop(){await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}};}
 private async read(req:AsyncIterable<Uint8Array>){const chunks:Uint8Array[]=[];let total=0;for await(const chunk of req){total+=chunk.byteLength;if(total>this.options.maximumBodyBytes)throw new Error("Request body is too large");chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString("utf8"));}
}
