import type { KnowledgeGraphEdge, KnowledgeGraphEdgeId, KnowledgeGraphId, KnowledgeGraphNode, KnowledgeGraphNodeId, KnowledgeGraphRepository } from "@knowledgeos/knowledge-graph";
import type { SqliteExecutor, SqliteRow } from "@knowledgeos/local-library-sqlite";
const parseNode=(r:SqliteRow):KnowledgeGraphNode=>({graphId:String(r.graph_id) as KnowledgeGraphId,nodeId:String(r.node_id) as KnowledgeGraphNodeId,type:String(r.type),labels:JSON.parse(String(r.labels_json)),properties:JSON.parse(String(r.properties_json)),version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),...(r.deleted_at==null?{}:{deletedAt:String(r.deleted_at)})});
const parseEdge=(r:SqliteRow):KnowledgeGraphEdge=>({graphId:String(r.graph_id) as KnowledgeGraphId,edgeId:String(r.edge_id) as KnowledgeGraphEdgeId,fromNodeId:String(r.from_node_id) as KnowledgeGraphNodeId,toNodeId:String(r.to_node_id) as KnowledgeGraphNodeId,type:String(r.type),directed:Boolean(r.directed),weight:Number(r.weight),properties:JSON.parse(String(r.properties_json)),version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),...(r.deleted_at==null?{}:{deletedAt:String(r.deleted_at)})});
export class SqliteKnowledgeGraphRepository implements KnowledgeGraphRepository {
  constructor(private readonly sql:SqliteExecutor){}
  async getNode(g:KnowledgeGraphId,n:KnowledgeGraphNodeId){const x=await this.sql.execute<SqliteRow>('select * from knowledge_graph_nodes where graph_id=? and node_id=?',[g,n]);return x.rows[0]?parseNode(x.rows[0]):undefined;}
  async getEdge(g:KnowledgeGraphId,e:KnowledgeGraphEdgeId){const x=await this.sql.execute<SqliteRow>('select * from knowledge_graph_edges where graph_id=? and edge_id=?',[g,e]);return x.rows[0]?parseEdge(x.rows[0]):undefined;}
  async upsertNode(n:KnowledgeGraphNode){await this.sql.execute(`insert into knowledge_graph_nodes(graph_id,node_id,type,labels_json,properties_json,version,created_at,updated_at,deleted_at) values(?,?,?,?,?,?,?,?,?) on conflict(graph_id,node_id) do update set type=excluded.type,labels_json=excluded.labels_json,properties_json=excluded.properties_json,version=excluded.version,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at`,[n.graphId,n.nodeId,n.type,JSON.stringify(n.labels),JSON.stringify(n.properties),n.version,n.createdAt,n.updatedAt,n.deletedAt??null]);}
  async upsertEdge(e:KnowledgeGraphEdge){await this.sql.execute(`insert into knowledge_graph_edges(graph_id,edge_id,from_node_id,to_node_id,type,directed,weight,properties_json,version,created_at,updated_at,deleted_at) values(?,?,?,?,?,?,?,?,?,?,?,?) on conflict(graph_id,edge_id) do update set from_node_id=excluded.from_node_id,to_node_id=excluded.to_node_id,type=excluded.type,directed=excluded.directed,weight=excluded.weight,properties_json=excluded.properties_json,version=excluded.version,updated_at=excluded.updated_at,deleted_at=excluded.deleted_at`,[e.graphId,e.edgeId,e.fromNodeId,e.toNodeId,e.type,e.directed?1:0,e.weight,JSON.stringify(e.properties),e.version,e.createdAt,e.updatedAt,e.deletedAt??null]);}
  async listNodes(g:KnowledgeGraphId){const x=await this.sql.execute<SqliteRow>('select * from knowledge_graph_nodes where graph_id=? and deleted_at is null order by node_id',[g]);return x.rows.map(parseNode);}
  async listEdges(g:KnowledgeGraphId){const x=await this.sql.execute<SqliteRow>('select * from knowledge_graph_edges where graph_id=? and deleted_at is null order by edge_id',[g]);return x.rows.map(parseEdge);}
}
export const knowledgeGraphSqliteMigrations=[{id:'0011_knowledge_graph_core',sql:`create table if not exists knowledge_graph_nodes(graph_id text not null,node_id text not null,type text not null,labels_json text not null,properties_json text not null,version integer not null,created_at text not null,updated_at text not null,deleted_at text,primary key(graph_id,node_id)); create table if not exists knowledge_graph_edges(graph_id text not null,edge_id text not null,from_node_id text not null,to_node_id text not null,type text not null,directed integer not null,weight real not null,properties_json text not null,version integer not null,created_at text not null,updated_at text not null,deleted_at text,primary key(graph_id,edge_id),foreign key(graph_id,from_node_id) references knowledge_graph_nodes(graph_id,node_id),foreign key(graph_id,to_node_id) references knowledge_graph_nodes(graph_id,node_id)); create index if not exists idx_kg_edges_from on knowledge_graph_edges(graph_id,from_node_id,type); create index if not exists idx_kg_edges_to on knowledge_graph_edges(graph_id,to_node_id,type);`} ] as const;
