@startuml Deployment_iPhoneOS

title KnowledgeOS - iPhoneOS Deployment

node "iPhone" {
  artifact "KnowledgeOS iPhone App"
  database "Local Storage"
}

node "NAS" {
  database "Library Source of Truth"
}

"KnowledgeOS iPhone App" --> "Local Storage"
"KnowledgeOS iPhone App" --> "Library Source of Truth"

@enduml