@startuml ExportDocument

title Export Document

actor User

participant UI

participant "Export Engine" as Export

participant "Library Engine" as Library

participant "Render Engine" as Render

User -> UI : Exportar

UI -> Export : ExportDocument()

Export -> Library : Obtener UDM

Library --> Export : Documento

Export -> Render : Render()

Render --> Export : Representación

Export --> UI : Archivo generado

@enduml