import { createServer } from "node:http";
import { authorize, PersonalKnowledgeTokenService } from "@knowledgeos/personal-knowledge-auth";
import type { PersonalKnowledgeReplicaRecord } from "@knowledgeos/personal-knowledge-sync";

export interface IncrementalSyncStore { append(ownerId:string,deviceId:string,record:PersonalKnowledgeReplicaRecord,occurredAt:string):Promise<number>; pull(ownerId:string,afterCursor:number,limit:number):Promise<readonly {cursor:number;record:PersonalKnowledgeReplicaRecord}[]>; }
export interface ApiOptions {readonly host:string;readonly port:number;readonly tokenSecret:string;readonly maximumPullRecords:number;}
export class PersonalKnowledgeSyncApiServer {
 public constructor(private readonly store:IncrementalSyncStore,private readonly options:ApiOptions){}
 async start(){const tokens=new PersonalKnowledgeTokenService(this.options.tokenSecret);const server=createServer(async(req,res)=>{try{const raw=req.headers.authorization;if(typeof raw!=="string"||!raw.startsWith("Bearer "))throw new Error("Unauthorized");const claims=tokens.verify(raw.slice(7),Math.floor(Date.now()/1000));const url=new URL(req.url??"/","http://localhost");if(url.pathname!=="/v1/personal-knowledge/events"){this.json(res,404,{error:"not-found"});return;}const ownerId=url.searchParams.get("ownerId")??claims.sub;const deviceId=url.searchParams.get("deviceId")??claims.deviceId;authorize(claims,ownerId,deviceId,"pk:sync");if(req.method==="POST"){const body=await this.body(req) as {records:readonly PersonalKnowledgeReplicaRecord[]};let cursor=0;for(const record of body.records)cursor=await this.store.append(ownerId,deviceId,record,new Date().toISOString());this.json(res,200,{acceptedRecords:body.records.length,cursor});return;}if(req.method==="GET"){const after=Number(url.searchParams.get("after")??"0");const limit=Math.min(Number(url.searchParams.get("limit")??this.options.maximumPullRecords),this.options.maximumPullRecords);const events=await this.store.pull(ownerId,after,limit);this.json(res,200,{events,nextCursor:events.at(-1)?.cursor??after});return;}this.json(res,405,{error:"method-not-allowed"});}catch(e){this.json(res,401,{error:e instanceof Error?e.message:"unauthorized"});}});await new Promise<void>(r=>server.listen(this.options.port,this.options.host,r));const a=server.address();if(!a||typeof a==="string")throw new Error("No address");return{host:a.address,port:a.port,stop:()=>new Promise<void>((r,j)=>server.close(e=>e?j(e):r()))};}
 private async body(req:AsyncIterable<Uint8Array>):Promise<unknown>{const c=[];for await(const x of req)c.push(x);return JSON.parse(Buffer.concat(c).toString("utf8"));}
 private json(res:{statusCode:number;setHeader(n:string,v:string|number):void;end(d?:string):void},status:number,body:unknown){res.statusCode=status;res.setHeader("content-type","application/json");res.end(JSON.stringify(body));}
}
