import assert from "node:assert/strict"; import test from "node:test";
import {AIEngine,InMemoryAIProvider,InMemoryAISession} from "../src/index.js"; import {CancellationNone,CancellationSource} from "@knowledgeos/kernel";
const model={id:"in-memory:text",providerId:"in-memory",name:"In-Memory",local:true,contextWindow:8192,capabilities:["text-generation","embeddings","summarization"] as const,metadata:{}};
test("session generates",async()=>{const r=await new InMemoryAISession(model).generate({messages:[{role:"user",content:"Hello"}]});assert.equal(r.content,"Response: Hello");});
test("session embeds",async()=>{const r=await new InMemoryAISession(model).embed(["knowledge"]);assert.equal(r.vectors[0]?.length,4);});
test("engine lifecycle",async()=>{const e=new AIEngine();await e.registerProvider(new InMemoryAIProvider([model]));const c={cancellation:CancellationNone,metadata:{}};await e.initialize(c);await e.start(c);assert.equal((await e.generate({messages:[{role:"user",content:"KnowledgeOS"}]})).modelId,model.id);await e.stop(c);await e.dispose(c);});
test("engine cancellation",async()=>{const e=new AIEngine();await e.registerProvider(new InMemoryAIProvider([model]));const c={cancellation:CancellationNone,metadata:{}};await e.initialize(c);await e.start(c);const s=new CancellationSource();s.cancel(new Error("cancelled"));await assert.rejects(()=>e.generate({messages:[{role:"user",content:"x"}]},{cancellation:s.token}));});
test("engine summarizes",async()=>{const e=new AIEngine();await e.registerProvider(new InMemoryAIProvider([model]));const c={cancellation:CancellationNone,metadata:{}};await e.initialize(c);await e.start(c);assert.equal((await e.summarize({messages:[{role:"user",content:"abc"}]})).content,"Response: abc");});
test("engine embeds",async()=>{const e=new AIEngine();await e.registerProvider(new InMemoryAIProvider([model]));const c={cancellation:CancellationNone,metadata:{}};await e.initialize(c);await e.start(c);assert.equal((await e.embed(["a","b"])).vectors.length,2);});
