import type { PageAnchor, PersonalKnowledgeAnchor, TextAnchor } from "@knowledgeos/personal-knowledge";
import type { AnchorConfidence, AnchorResolution, VersionTextSnapshot } from "./model.js";
import { bestApproximate } from "./similarity.js";
const confidence=(s:number):AnchorConfidence=>s>=.999?"perfect":s>=.85?"high":s>=.65?"medium":s>=.45?"low":"orphan";
export class PersonalKnowledgeAnchorResolver{
 resolve(anchor:PersonalKnowledgeAnchor,from:VersionTextSnapshot,to:VersionTextSnapshot):AnchorResolution{if(String(anchor.publicationId)!==String(to.publicationId))return this.orphan(anchor,"Target snapshot belongs to another publication");return anchor.kind==="page"?this.page(anchor,to):this.text(anchor,from,to);}
 private text(anchor:TextAnchor,_from:VersionTextSnapshot,to:VersionTextSnapshot):AnchorResolution{const selected=anchor.selectedText??"";if(selected&&to.text.slice(anchor.startOffset,anchor.endOffset)===selected)return {original:anchor,resolved:{...anchor,versionId:to.versionId},strategy:"exact-offset",confidence:"perfect",score:1,orphaned:false,explanation:"Text remains at original offsets"};if(selected){const i=to.text.indexOf(selected);if(i>=0)return {original:anchor,resolved:{...anchor,versionId:to.versionId,startOffset:i,endOffset:i+selected.length},strategy:"exact-text",confidence:"high",score:.95,orphaned:false,explanation:"Text found at new offset"};const m=bestApproximate(to.text,selected);if(m&&m.score>=.45)return {original:anchor,resolved:{...anchor,versionId:to.versionId,startOffset:m.startOffset,endOffset:m.endOffset,selectedText:to.text.slice(m.startOffset,m.endOffset)},strategy:"approximate-text",confidence:confidence(m.score),score:m.score,orphaned:false,explanation:"Approximate text match"};}return this.orphan(anchor,"No reliable text match");}
 private page(anchor:PageAnchor,to:VersionTextSnapshot):AnchorResolution{const count=to.pageStarts?.length??0;if(count&&anchor.pageNumber<=count)return {original:anchor,resolved:{...anchor,versionId:to.versionId},strategy:"page-position",confidence:"medium",score:.7,orphaned:false,explanation:"Referenced page remains valid"};return this.orphan(anchor,"Referenced page is unavailable");}
 private orphan(anchor:PersonalKnowledgeAnchor,explanation:string):AnchorResolution{return {original:anchor,strategy:"unresolved",confidence:"orphan",score:0,orphaned:true,explanation};}
}
