legend right

|= Tipo |= Descripción |

| Kernel | Núcleo |

| Platform | Servicios compartidos |

| Engine | Motor funcional |

| Model | Modelo de dominio |

| External | Sistema externo |

endlegend
